version: '2'

services:
  db:
    image: 'postgres:9.6'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - app-gems:/usr/local/bundle
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DISABLE_SPRING=1

# store data on the host to persist between builds
volumes:
  postgres-data:
  app-gems:

