default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: crud_development
  username: postgres
  password:
  host: db

test:
  <<: *development
  database: crud_test

production:
  <<: *default
  database: crud_production
  username: crud
  password: <%= ENV['CRUD_DATABASE_PASSWORD'] %>
